name: GitHub Actions Demo

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 24f2008801@ds.study.iitm.ac.in
        run: echo "Hello, world!"

      - name: Finish
        run: echo "Workflow completed"
